### ISSUE TITLE
Error in prog_x_st[1:prog_bar_length]

### ISSUE THREAD

**Issue by stmarcin** [16EAGLE/moveVis#25] opened 2018-09-26 08:02 UTC
Hello again,
Not sure if the previous issue is solved (I still get info: "cannot open URL", but only once and the script seems to proceed further). But, I get another one:

> Building map elements...
Error in prog_x_st[1:prog_bar_length] : 
  only 0's may be mixed with negative subscripts

It confused me as I used to work with the same file and it worked... Attached please find the csv file and the code I use is this:

```
GTFS <- read.csv("GTFS_M5.csv")
GTFS$arrival_time <- as.POSIXct(strptime(GTFS$arrival_time, "%H:%M:%S", tz = "UTC"))
conv_dir <- get_libraries()

out_dir <- paste0(getwd(),"/test")

GTFS_ani <- split(move(GTFS$stop_lon, GTFS$stop_lat, proj=CRS("+proj=longlat +ellps=WGS84"),
                       time = GTFS$arrival_time, animal=GTFS$trip_id, data=GTFS))

animate_move(GTFS_ani, out_dir, out_name = "test5", conv_dir = conv_dir, 
             paths_mode = "true_data", frames_nmax = 10,
             log_level = 1, out_format = "mp4",
             map_type = "roadmap")
```

[GTFS_M5.zip](https://github.com/16EAGLE/moveVis/files/2418664/GTFS_M5.zip)

I saw a similar topic on closed issues, however, I'm not sure whether it was solved (I am using the newest version from CRAN: 0.9.8).

**Comment by 16EAGLE** [comment] 2018-10-10 09:06
Thanks for reporting the issue. I see you set `frames_nmax` to 10. Since `tail_elements` defaults to 10, only a single frame remains, probably resulting in the cryptic error. Could you try if the problem still occurs if you set `frames_nmax = 20` or higher? I will implement code to catch the error to make it less cryptic than the one you saw.

**Comment by 16EAGLE** [comment] 2018-11-09 15:05
I close this due to no further replies. If the issue is still pending, please reopen.

**Closed by 16EAGLE** 2018-11-09 15:05 UTC
Labels: enhancement
