### ISSUE TITLE
Issue converting data.frame to moveStack object

### ISSUE THREAD

**Issue by sskalos4** [16EAGLE/moveVis#37] opened 2019-02-26 05:57 UTC
[move_37_sample.xlsx](https://github.com/16EAGLE/moveVis/files/2903962/move_37_sample.xlsx)

Hello,

I'm running into the error below when I run the following code. I'm a fairly new R users, so I'm not sure how to troubleshoot this error. As far as I can tell, my data file is setup similarly to the example data (attached as an .xlsx file). Help appreciated!

move_df <- methods::as(move_37_sample, "data.frame")

move_df$dt <- as.POSIXct(strptime(move_df$dt,"%m/%d/%Y %H:%M:%S", tz = "UTC"))
move_df$id<- as.factor(move_df$id)

df2move(move_df,
        proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
        x = "lon", y = "lat", time = "dt", track_id = "id")

Error in df[, track_id] == x : 
  comparison of these types is not implemented
In addition: Warning message:
In which(df[, track_id] == x) :
  Incompatible methods ("Ops.data.frame", "Ops.factor") for "=="

**Comment by 16EAGLE** [comment] 2019-02-26 09:02
Hello,

I could not reproduce the exact error you got, however this works:

Since your code does not include how you loaded your data, I used `read_xlsx` from the `readxl` package, thus converting `move_df$dt` into `POSIXct` is not needed:

```
library(readxl)
move_df <- as.data.frame(read_xlsx("dev/user_data/move_37_sample.xlsx"))`
```

Turning this into a `move` object fails, since every second row in your `move_37_sample.xlsx` dataset is a duplicate of the prior row:

```R
m <- df2move(move_df,
             proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
             x = "lon", y = "lat", time = "dt", track_id = "id")

>>> Error in validityMethod(as(object, superClass)) : 
            The dataset includes double timestamps first one:2018-02-06) 
```

When removing these duplicated rows, `df2move` works fine:
```R
move_df <- move_df[!duplicated(move_df),]
m <- df2move(move_df,
             proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
             x = "lon", y = "lat", time = "dt", track_id = "id")
```
Hope, this helps. Please let me know, if there are any further issues.

**Comment by sskalos4** [comment] 2019-02-27 17:08
Thanks, that did the trick. I think the duplicates were a product of data manipulation on my end. I didn't see that at all!

**Closed** 2019-02-27 22:28 UTC
