### ISSUE TITLE
Adding scalebar: Error in .pointsToMatrix(p1) : longitude < -360  

### ISSUE THREAD

**Issue by JSC2019** [16EAGLE/moveVis#68] opened 2019-05-16 15:03 UTC
Hello,
I am having some issues when trying to add the scale bar to the frame. If I don't add any scale bar, then everything works fine and I get the frames and video. This is the error I get:
Error in .pointsToMatrix(p1) : longitude < -360

My study area is small, so the scale bar should be lower than 1 km, so I am guessing it has to do with that. Is there any way to work around it.
This is my code. Thanks for your help.

GPS<-df2move(GPS, proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
             x = "Longitude" , y = "Latitude", time = "dt", track_id = "ID")

unique(timestamps(GPS))
timeLag(GPS, unit = "mins")

move_data <- align_move(GPS, res = 240, digit = 0, unit = "secs")

move_data <- sp::spTransform(move_data, crs("+init=epsg:3857"))
frames <- frames_spatial(move_data, path_colours = c("red"),
                         map_service = "osm",path_legend_title = NULL, map_type = "streets", map_res = 0.8, equidistant = F)

frames <- add_labels(frames, title = " (UK) 2019",
                     x = "Longitude", y = "Latitude") %>% 
  add_progress() %>% 
  add_scalebar() %>% 
  add_northarrow() %>% 
  add_timestamps(move_data, type = "label")

**Comment by 16EAGLE** [comment] 2019-05-21 08:14
Hello,
could you please run `apply(sp::coordinates(GPS), MARGIN = 2, range)` with your `GPS` object that you generated using `df2move` and post the result? This will display the minimum and maximum for both your longitude and latitude values.

Apart from that, the distance that should be displayed by the scale bar can be set in km using the `distance` argument in `add_scalebar()`, e.g. `add_scalebar(distance = 0.2)`.

**Comment by JSC2019** [comment] 2019-05-21 16:20
Hello,
I get:
> apply(sp::coordinates(GPS), MARGIN = 2, range)
     coords.x1 coords.x2
[1,]  -0.97877  53.05509
[2,]  -0.95424  53.06505
I have tried several things with the add_scalebar() but still not working, as I said it before, if I don't include this command, the video is generated without any problems, but without scale. Any idea what else could I try? Thanks,

**Comment by 16EAGLE** [comment] 2019-05-22 09:12
Thanks for the info. Could you provide me with a sample of your data set with which I can reproduce the error? Otherwise it is difficult to track it down.

**Comment by JSC2019** [comment] 2019-05-22 10:24
[GPS.xlsx](https://github.com/16EAGLE/moveVis/files/3206925/GPS.xlsx)
Sure, please find attached it. Thanks a lot for your help.
Regards,

**Comment by JSC2019** [comment] 2019-07-10 09:57
Hi,
Just wondering if you had time to have a look at the data.
Thanks for the help!
Regard,

**Comment by 16EAGLE** [comment] 2020-04-29 12:34
Hi,

sorry, I lost track of this issue. This should be fixed by now. Originally, add_scalebar had issues with projections other than unprojected lat/lon. Your code works for me with the latest version:

```R
library(moveVis)

gps <- xlsx::read.xlsx("GPS.xlsx", sheetIndex = 1)[1:58,1:6]
gps$dt <- as.POSIXct(gps$dt, format = "%d/%m/%Y %H:%M:%S")

GPS <- df2move(gps, proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
             x = "Longitude" , y = "Latitude", time = "dt", track_id = "ID")

unique(timestamps(GPS))
timeLag(GPS, unit = "mins")

move_data <- align_move(GPS, res = 240, digit = 0, unit = "secs")
move_data <- sp::spTransform(move_data, crs("+init=epsg:3857"))

frames <- frames_spatial(move_data, path_colours = c("red"),
                         map_service = "osm", path_legend_title = NULL, map_type = "streets", map_res = 0.8, equidistant = F)

frames <- add_labels(frames, title = " (UK) 2019",
                     x = "Longitude", y = "Latitude") %>%
  add_progress() %>%
  add_scalebar() %>%
  add_northarrow() %>%
  add_timestamps(move_data, type = "label")
```

![plot_zoom_png](https://user-images.githubusercontent.com/23257860/80596372-8dc35300-8a26-11ea-9970-c9c26004325d.png)

**Closed by 16EAGLE** 2020-04-29 12:34 UTC
